apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.4
        args: ["start", "--cache-stack=kubernetes"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: jgroups.dns.query
          value: "keycloak"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: PassKhongChilaPasss
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_URL_HOST
          value: 10.86.224.19
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"          
        ports:
          - name: jgroups
            containerPort: 7600
          - name: https
            containerPort: 8443
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 1
